title:              Park Blog
email:              img1518@gmail.com
description:        1011011101111101
author:             Park Jong Moon
baseurl:            ""
url:                "https://Entar0.github.io"

# Social Profiles
twitter_username:   
github_username:    ENTAR0
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
